#!/bin/bash
# shabang


#if param len is 0 mando errore (-z è zero lenght)
if [ -z "$1" ]; then
    echo "Uso: gamblang <file.gamblang>"
    exit 1
fi

#path assoluto
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
python3 "$SCRIPT_DIR/main.py" "$1"
